version: "3.7"

services:
  
  selfsovereignai:
    container_name: selfsovereignai
    build:
      context: .
    ports:
      - 8501:8501
    volumes:
      - ./:/app
      - ./data:/data/
  
  premd:
    container_name: premd
    image: ghcr.io/premai-io/premd:latest
    ports:
      - 8000:8000
    restart: on-failure
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PREM_REGISTRY_URL=https://raw.githubusercontent.com/premAI-io/prem-registry/main/manifests.json
      - SENTRY_DSN=https://75592545ad6b472e9ad7c8ff51740b73@o1068608.ingest.sentry.io/4505244431941632    

  prem_app:
    container_name: prem_app
    image: ghcr.io/premai-io/prem-app:latest
    ports:
      - 1420:1420
    environment:
      - VITE_DESTINATION=browser
      - VITE_IS_PACKAGED=true
      - VITE_BACKEND_URL=http://premd:8000

  # tor:
  #   container_name: tor
  #   restart: unless-stopped
  #   build:
  #     context: tor
  #     dockerfile: Dockerfile
  #   network_mode: "host"
  #   ports:
  #     - 9050:9050
  #     - 9051:9051